/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
     void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appQuotesHasMoreThanTwo() {
        App classUnderTest = new App();
        classUnderTest.getGreeting();
        assertTrue(classUnderTest.quotes.stream().count()>=2, "App quotes should have more than 2 quotes");
    }


}
