/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import java.lang.reflect.Type;
import java.util.ArrayList;
import com.google.gson.Gson;
import java.io.Reader;
import java.nio.file.*;

import com.google.gson.reflect.TypeToken;

public class App {
    public ArrayList<Quote> quotes = new ArrayList<Quote>();
    public Quote[] q;

    public void quotesFileToQuotesArray(String filename){
        //get json from file and convert to POJO:
        try {
            // create Gson instance
            Gson gson = new Gson();

            // create a reader
            Reader reader = Files.newBufferedReader(Paths.get(filename));

            Type QuoteListType = new TypeToken<ArrayList<Quote>>(){}.getType();

            // convert JSON string to User object
             quotes = gson.fromJson(reader, QuoteListType);
             for(Quote ea:quotes){
             //    System.out.println(ea.text);
             }
            // close reader
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    public String getRandomQuote(ArrayList<Quote> _quoteArray){
        //System.out.print("Array Count");
       // System.out.println(Integer.toString((int) (Math.random() * _quoteArray.stream().count())));
        int randomIndex = (int) (Math.random() * _quoteArray.stream().count());

        //System.out.print("ArrayIndex:");
        //System.out.println(randomIndex);
        return _quoteArray.get(randomIndex).toString();
    }

    public String getGreeting() {

        try {
            quotesFileToQuotesArray( "./src/main/resources/recentquotes.json");
        } catch (Exception e) {
            System.out.println("Working Directory = " + System.getProperty("user.dir"));
            System.out.println(e.toString());
        }
        String greeting = getRandomQuote(quotes);

        return greeting;
    }

    public static void main(String[] args) {
        System.out.println("Working Directory = " + System.getProperty("user.dir"));
        System.out.println("Quote Of The Day:");
        System.out.println(new App().getGreeting());
    }
}
