/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import java.lang.reflect.Type;
import java.util.ArrayList;
import com.google.gson.Gson;
import java.io.Reader;
import java.nio.file.*;

import com.google.gson.reflect.TypeToken;

public class App {
    public ArrayList<Quote> quotes = new ArrayList<Quote>();

    public void quotesFileToQuotesArray(String filename){
        //get json from file and convert to POJO:
        //note that it doesn't return an Array, but modifies
        //the public quotes array in the class.

        try {
            // create Gson instance
            Gson gson = new Gson();

            // create a reader
            Reader reader = Files.newBufferedReader(Paths.get(filename));

            //This line from googling gets the correct type for an ArrayList<Quote>
            Type QuoteListType = new TypeToken<ArrayList<Quote>>(){}.getType();

            // convert JSON file to ArrayList of Quote object
             quotes = gson.fromJson(reader, QuoteListType);


            // close reader
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    public String getRandomQuote(ArrayList<Quote> _quoteArray){
        int randomIndex = (int) (Math.random() * _quoteArray.stream().count());

        return _quoteArray.get(randomIndex).toString();
    }

    public String getGreeting() {

        try {
            quotesFileToQuotesArray( "./src/main/resources/recentquotes.json");
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        String greeting = getRandomQuote(quotes);

        return greeting;
    }

    public static void main(String[] args) {
        System.out.println("Quote Of The Day:");
        System.out.println(new App().getGreeting());
    }
}
